apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-demo-go-app
  namespace: tenant2
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: flux-demo-go-app
  template:
    metadata:
      labels:
        app: flux-demo-go-app
    spec:
      containers:
      - name: flux-demo-go-app
        image: docker.io/hpark2330/flux-demo-go-app:1.0.1 # {"$imagepolicy": "tenant2:mrt-demo-go-app-image-policy"}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
